# syntax=docker/dockerfile:1

# ============================
# Stage 1 - Build React App
# ============================

FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci \
    --no-audit \
    --no-fund

COPY . .

RUN npm run build


# ============================
# Stage 2 - Serve with Nginx
# ============================

FROM nginxinc/nginx-unprivileged:stable-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build \
     /app/dist \
     /usr/share/nginx/html

EXPOSE 8080
